/* Data */



/* Functions */

script_env_2_enable = 0x08069940|1;
help_system_disable_sp198 = 0x0812B478|1;
pal_set_something = 0x08070588|1;
overworld_free_bgmaps = 0x080563F0|1;
lcd_io_set = 0x08000A38|1;
vblank_hander_set = 0x080006F4|1;
vblank_hander_callback = 0x08046FC0|1;
gpu_tile_bg_drop_all_sets = 0x08001618|1;
bg_positions_reset = 0x0812D594|1;
reset_and_init_alot = 0x080F4E24|1;


/* Custom data */

